# Generated by Django 4.2 on 2023-04-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='template',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\PROJECT NM\\Scripts\\project\\static\\data'),
        ),
    ]
