# Generated by Django 4.2 on 2023-04-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_objectdetector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectDetector',
        ),
    ]
