# Generated by Django 4.2 on 2023-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_objectdetector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='D:\\PROJECT NM\\Scripts\\project\\data')),
            ],
        ),
    ]
